POST https://vssps.dev.azure.com/{organization}/_apis/graph/users?api-version=7.1-preview.1
Authorization: Basic :PAT
Content-Type: application/json

{
  "principalName": "jtseng@vscsi.us"
}

# {
#   "originId": "e97b0e7f-0a61-41ad-860c-748ec5fcb20b"
# }
# //Add an AAD user by OID

# {
#   "principalName": "jtseng@vscsi.us"
# }
# //Add an AAD user by UPN

# {
#   "originId": "27dbfced-5593-4756-98a3-913c39af7612",
#   "storageKey": "9b71f216-4c4f-6b74-a911-efb0fa9c777f"
# }
# //Add an AAD user with a custom storage key
