name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_Solution:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore AzureDevOps.slnx

      - name: Build AzureDevOps.slnx
        run: dotnet build AzureDevOps.slnx --no-restore --configuration Release

      - name: Run AzureDevOps.slnx tests
        run: dotnet test AzureDevOps.slnx --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
        env:
          AZURE_DEV_OPS_ORGANISATION_NAME: ${{ secrets.AZURE_DEV_OPS_ORGANISATION_NAME }}
          AZURE_DEV_OPS_PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_DEV_OPS_PERSONAL_ACCESS_TOKEN }}

      - name: Publish AzureDevOpsRestClient
        run: >
          dotnet publish ./src/AzureDevOpsRestClient/AzureDevOpsRestClient.csproj
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -o ./publish
        env:
          SYNCFUSION_LICENSE_KEY: ${{ secrets.SYNCFUSION_LICENSE_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzureDevOpsRestClient-win-x64
          path: ./publish