@WebApp_HostAddress = https://dev.azure.com/{organization-name}

POST {{WebApp_HostAddress}}/_apis/accesscontrolentries/2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87?api-version=7.1
Authorization: Basic {Token}
Content-Type: application/json

{
  "token": "repoV2/{projectId}/{repositoryId}",
  "merge": false,
  "accessControlEntries": [
    {
      "descriptor": "Microsoft.IdentityModel.Claims.ClaimsIdentity;{id}\\AdeleV@xxx.onmicrosoft.com",
      "allow": 0,
      "deny": 512
    }
  ]
}

###
