POST https://vgpbm3s3-7186.euw.devtunnels.ms/webhooks/azuredevops/git-repo-created
Content-Type: application/json; charset=utf-8

{
    "id": "a0a0a0a0-bbbb-cccc-dddd-e1e1e1e1e1e1",
    "eventType": "git.repo.created",
    "publisherId": "tfs",
    "message": {
        "text": "A new Git repository was created with name Fabrikam-Fiber-Git and ID c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3.",
        "html": "A new Git repository was created with name <a href=\"https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/\">Fabrikam-Fiber-Git</a> and ID c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3.",
        "markdown": "A new Git repository was created with name [Fabrikam-Fiber-Git](https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/) and ID `c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3`."
    },
    "detailedMessage": {
        "text": "A new Git repository was created with name Fabrikam-Fiber-Git and ID c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3.",
        "html": "A new Git repository was created with name <a href=\"https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/\">Fabrikam-Fiber-Git</a> and ID c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3.",
        "markdown": "A new Git repository was created with name [Fabrikam-Fiber-Git](https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git/) and ID `c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3`."
    },
    "resource": {
        "repository": {
            "id": "c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3",
            "name": "Fabrikam-Fiber-Git",
            "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/git/repositories/c2c2c2c2-dddd-eeee-ffff-a3a3a3a3a3a3",
            "project": {
                "id": "00aa00aa-bb11-cc22-dd33-44ee44ee44ee",
                "name": "Fabrikam-Fiber-Git",
                "url": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_apis/projects/00aa00aa-bb11-cc22-dd33-44ee44ee44ee",
                "state": "wellFormed",
                "revision": 11,
                "visibility": "private",
                "lastUpdateTime": "2025-06-12T20:22:53.7494088+00:00"
            },
            "defaultBranch": "refs/heads/main",
            "size": 728,
            "remoteUrl": "https://fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git",
            "sshUrl": "ssh://git@ssh.fabrikam-fiber-inc.visualstudio.com/v3/DefaultCollection/Fabrikam-Fiber-Git",
            "isDisabled": false
        },
        "initiatedBy": {
            "displayName": "Ivan Yurev",
            "id": "22cc22cc-dd33-ee44-ff55-66aa66aa66aa",
            "uniqueName": "user@fabrikamfiber.com"
        },
        "utcTimestamp": "2022-12-12T12:34:56.5498459Z"
    },
    "resourceVersion": "1.0-preview.1",
    "resourceContainers": {
        "collection": {
            "id": "b1b1b1b1-cccc-dddd-eeee-f2f2f2f2f2f2"
        },
        "account": {
            "id": "bbbb1b1b-cc2c-dd3d-ee4e-ffffff5f5f5f"
        },
        "project": {
            "id": "00aa00aa-bb11-cc22-dd33-44ee44ee44ee"
        }
    },
    "createdDate": "2025-06-12T20:22:53.818Z"
}